plugins {
    id 'geoclient.library-conventions'
    id 'geoclient.test-conventions'
}

dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    implementation(libs.spring.boot.starter.logging)
    implementation(project(':geoclient-jni'))
    implementation(project(':geoclient-xml'))
    implementation('org.apache.commons:commons-lang3')
    testImplementation(libs.spring.boot.starter.test)
    testImplementation(testFixtures(project(':geoclient-jni')))
}

testing {
    suites {
        integrationTest {
            dependencies {
                implementation(project(':geoclient-jni'))
                implementation(project(':geoclient-xml'))
                implementation(testFixtures(project(':geoclient-jni')))
            }
        }
    }
}
