import org.gradle.api.plugins.jvm.JvmTestSuite
import org.gradle.api.tasks.testing.Test
import org.gradle.testing.jacoco.tasks.JacocoReport

plugins {
    id('java')
    id('java-test-fixtures')
    id('jacoco')
}

import org.gradle.api.plugins.jvm.JvmTestSuite

void configureMockitoAgent(JvmTestSuite suite) {
    String artifactName = libs.mockito.core.get().module.name

    suite.targets.all {
        testTask.configure {
            doFirst {
                def mockitoJar = classpath.find { file -> 
                    file.name.startsWith("${artifactName}-") && file.name.endsWith(".jar")
                }
                
                if (mockitoJar) {
                    jvmArgs  "-Xshare:off", "-javaagent:${mockitoJar.absolutePath}"
                }
            }
        }
    }
}

testing {
    suites {
        configureEach { 
            useJUnitJupiter()
            dependencies { 
                implementation(platform(libs.spring.boot.dependencies))
                implementation(libs.spring.boot.starter.logging)
                implementation(libs.mockito.core)
            }
            
        }
        test {
            targets {
                all {
                    testTask.configure {
                        testLogging {
                            events "failed", "skipped"
                            exceptionFormat = "short"
                        }
                    }
                }
            }
        }

        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(testing.suites.test)
                        environment("GEOFILES", '/opt/geosupport/current/fls/')
                        testLogging {
                            // options for log level LIFECYCLE
                            events "failed", "skipped"
                            exceptionFormat = "short"
                            showStandardStreams = false

                            debug {
                                events "failed", "skipped", "passed"
                                exceptionFormat = "full"
                                showStandardStreams = false
                            }

                            info {
                                events "failed", "skipped", "passed"
                                showStandardStreams = false
                            }
                        }
                    }
                }
            }
        }
    }

    suites.all { JvmTestSuite suite ->
        configureMockitoAgent(suite)
    }
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
    dependsOn(tasks.named('jacocoTestReport'))
    dependsOn(tasks.named('jacocoIntegrationTestReport'))
}

tasks.named('jacocoTestReport') {
    dependsOn(testing.suites.test)
    reports {
        xml.required = true
    }
}

tasks.register('jacocoIntegrationTestReport', JacocoReport) {
    group = 'verification'
    description = 'Generates code coverage report for the integrationTest task.'
    dependsOn(testing.suites.integrationTest)
    executionData(layout.buildDirectory.file('jacoco/integrationTest.exec'))
    classDirectories.setFrom(files(project.sourceSets.main.output))
    sourceDirectories.setFrom(files(project.sourceSets.main.allSource.srcDirs))
    reports {
        xml.required = true
        html.required = true
    }
}
