import org.gradle.api.plugins.jvm.JvmTestSuite
import org.gradle.api.tasks.testing.Test
import org.gradle.testing.jacoco.tasks.JacocoReport

plugins {
    id('java')
    id('java-test-fixtures')
    id('jacoco')
}

configurations {
    mockitoAgent
}

dependencies {
    //
    // The special configuration for mockito-core is necessary to avoid a
    // warning on JDK 21 due to restrictions on instrumentation.
    // For more details see:
    // https://javadoc.io/static/org.mockito/mockito-core/5.23.0/org.mockito/org/mockito/Mockito.html#mockito-instrumentation
    //
    // NOTE: the mockito version is set in gradle/libs.versions.toml even
    // though it is part of the spring-boot-starter-test BOM.
    //
    // IMPORTANT: when upgrading spring-boot, this dependency must be manually
    // configured to use the proper version.
    //
    testFixturesImplementation 'org.springframework.boot:spring-boot-starter-logging'
    mockitoAgent(libs.mockito.core) {
        transitive = false
    }
}

testing {
    suites {
        test {
            useJUnitJupiter()

            dependencies {
                implementation platform(project(':platform'))
                implementation(libs.mockito.core)
                runtimeOnly 'org.junit.platform:junit-platform-launcher'
            }

            targets {
                all {
                    testTask.configure {
                        testLogging {
                            events "failed", "skipped"
                            exceptionFormat = "short"
                        }
                    }
                }
            }
        }

        integrationTest(JvmTestSuite) {
            dependencies {
                implementation project()
                implementation platform(project(':platform'))
                implementation(libs.mockito.core)
                implementation 'org.springframework.boot:spring-boot-starter-logging'
                runtimeOnly 'org.junit.platform:junit-platform-launcher'
            }

            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(testing.suites.test)
                        environment("GEOFILES", '/opt/geosupport/current/fls/')
                        testLogging {
                            // options for log level LIFECYCLE
                            events "failed", "skipped"
                            exceptionFormat = "short"
                            showStandardStreams = false

                            debug {
                                events "failed", "skipped", "passed"
                                exceptionFormat = "full"
                                showStandardStreams = false
                            }

                            info {
                                events "failed", "skipped", "passed"
                                showStandardStreams = false
                            }
                        }
                    }
                }
            }
        }
    }
}

tasks.named('check') {
    dependsOn(testing.suites.integrationTest)
    dependsOn(tasks.named('jacocoTestReport'))
    dependsOn(tasks.named('jacocoIntegrationTestReport'))
}

tasks.named('jacocoTestReport') {
    dependsOn(testing.suites.test)
    reports {
        xml.required = true
    }
}

tasks.register('jacocoIntegrationTestReport', JacocoReport) {
    group = 'verification'
    description = 'Generates code coverage report for the integrationTest task.'
    dependsOn(testing.suites.integrationTest)
    executionData(layout.buildDirectory.file('jacoco/integrationTest.exec'))
    classDirectories.setFrom(files(project.sourceSets.main.output))
    sourceDirectories.setFrom(files(project.sourceSets.main.allSource.srcDirs))
    reports {
        xml.required = true
        html.required = true
    }
}

tasks.withType(Test).configureEach {
    // Disable class data sharing to avoid warnings on JDK 21 due to restrictions on instrumentation.
    jvmArgs "-Xshare:off", "-javaagent:${configurations.mockitoAgent.asPath}"
    reports {
        junitXml {
            required = true
            outputPerTestCase = true
            mergeReruns = true
        }
    }
}