title: Geoclient Project Documentation
description: Geoclient is a geocoding API for New York City.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
exclude:
  - .devcontainer
  - .gradle
  - .local
  - .vscode
