version: '3'
services:
  geoclient:
    #image: mlipper/geoclient:2.0.0-rc.7
    build:
      context: .
      # TODO Use specific build stage or break into individual Dockerfiles
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: .env
    volumes:
      - "geosupport_home:${GEOSUPPORT_HOME}"
      - ".:/app"
    depends_on:
      - geosupport
  geosupport:
    #image: mlipper/geosupport-docker:1.0.9
    build:
      context: ./geosupport
      dockerfile: Dockerfile.geosupport
    volumes:
      - "geosupport_home:${GEOSUPPORT_HOME}"
    env_file: .env
volumes:
  geosupport_home:
  #external: true
