plugins {
    id 'distribution'
}

distributions {
    main {
        distributionBaseName = 'geoclient'
        contents {
            from(project(':geoclient-service').layout.buildDirectory.file('libs/geoclient.jar')) {
                into 'service'
            }
            from(project(':documentation').layout.buildDirectory.dir('docs/asciidoc')) {
                into 'docs'
            }
            from(rootProject.file('src/dist')) {
                include 'license.txt'
                include 'notice.txt'
            }
        }
    }
}

tasks.named('distZip') {
    dependsOn(':geoclient-service:dockerJar', ':documentation:asciidoctor')
}

tasks.named('distTar') {
    dependsOn(':geoclient-service:dockerJar', ':documentation:asciidoctor')
}

tasks.named('build') {
    setDependsOn([tasks.named('check')])
}
