plugins {
    id 'geoclient.library-conventions'
    id 'geoclient.test-conventions'
}

dependencies {
    // Version specified by catalog platform libs.junit-bom
    implementation 'org.junit.jupiter:junit-jupiter-api'
}

testing {
    suites {
        test {
            targets {
                all {
                    testTask.configure {
                        environment('GEOCLIENT_SERVICE_STATUS', 'running')
                        systemProperty('geoclient.service.status', 'running')
                    }
                }
            }
        }
    }
}