plugins {
    id 'geoclient.library-conventions'
    id 'geoclient.test-conventions'
}

dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    implementation(libs.spring.boot.starter.logging)
    implementation 'org.junit.jupiter:junit-jupiter-api'
}

testing {
    suites {
        test {
            targets {
                all {
                    testTask.configure {
                        environment('GEOCLIENT_SERVICE_STATUS', 'running')
                        systemProperty('geoclient.service.status', 'running')
                    }
                }
            }
        }
    }
}