/*
 * This source file was generated by the Gradle 'init' task
 */
package geoclientbuild.server;

import java.io.File;
import java.net.URI;
import java.util.List;

import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.file.RegularFile;
import org.gradle.api.logging.Logger;
import org.gradle.api.logging.Logging;
import org.gradle.api.provider.Provider;

public class GeoclientBuildServicePlugin implements Plugin<Project> {
    //private Logger logger = LoggerFactory.getLogger(GeoclientBuildServicePlugin.class);
    private Logger logger = Logging.getLogger(GeoclientBuildServicePlugin.class);

    public static final String APISERVER_INFO_TASK_NAME = "apiServerInfo";
    public static final String APISERVER_DEFAULT_OUTPUT_DIRECTORY = "api-server";
    public static final String APISERVER_DEFAULT_OUTPUT_FILE = "api-server.log";
    public static final String APISERVER_DEFAULT_PROFILE = "docsamples";
    public static final Long APISERVER_DEFAULT_WAIT_SECONDS = 8L;

    public void apply(Project project) {
        // Register the extension
        ApiServerExtension extension = registerExtension(project);

        //// Register the service
        //project.getGradle().getSharedServices().registerIfAbsent(ApiServer.SERVICE_NAME, ApiServer.class, spec -> {
        //    // Provide some parameters
        //    spec.getParameters().getScheme().set(extension.getScheme().get());
        //    spec.getParameters().getHost().set(extension.getHost().get());
        //    spec.getParameters().getPort().set(extension.getPort().get());
        //    spec.getParameters().getContextPath().set(extension.getContextPath().get());
        //    spec.getParameters().getApiServerJar().set(extension.getApiServerJar());
        //});

        // Register tasks
        project.getTasks().register(StartServer.TASK_NAME, StartServer.class, task -> {
                task.getApiServerJar().set(extension.getApiServerJar());
                task.getUri().set(baseUri(extension));
                List<String> args = new ArgumentsBuilder.BootArgumentsBuilder()
                    .host(extension.getHost().get())
                    .port(extension.getPort().get())
                    .contextPath(extension.getContextPath().get())
                    .profile(APISERVER_DEFAULT_PROFILE)
                    .build();
                task.getArguments().set(args);
                String outputFilePath = APISERVER_DEFAULT_OUTPUT_DIRECTORY + File.separator + APISERVER_DEFAULT_OUTPUT_FILE;
                Provider<RegularFile> outputFile = project.getLayout().getBuildDirectory().file(outputFilePath);
                task.getOutputFile().set(outputFile);
                task.getWaitSecondsAfterStart().set(extension.getWaitSecondsAfterStart());
            });

        project.getTasks().register(StopServer.TASK_NAME, StopServer.class, task -> {
            URI baseUri = baseUri(extension);
            task.getLogger().lifecycle("stopServer base URI: " + baseUri.toString());
            URI uri = baseUri(extension).resolve(StopServer.DEFAULT_ENDPOINT);
            task.getLogger().lifecycle("stopServer URI: " + uri.toString());
            task.getURI().set(uri);
            String outputFilePath = APISERVER_DEFAULT_OUTPUT_DIRECTORY + File.separator + APISERVER_DEFAULT_OUTPUT_FILE;
            Provider<RegularFile> outputFile = project.getLayout().getBuildDirectory().file(outputFilePath);
            task.getOutputFile().set(outputFile);
        });

        project.getTasks().register(APISERVER_INFO_TASK_NAME, task -> {
            String url = String.format("%s://%s:%d/%s",
                    extension.getScheme().get(),
                    extension.getHost().get(),
                    extension.getPort().get(),
                    extension.getContextPath().get());
            Provider<File> jarfile = extension.getApiServerJar().getAsFile();
            task.doLast(s -> {
                logger.lifecycle("ApiServer build service URL: " + url);
                logger.lifecycle("ApiServer JAR: " + jarfile.get().getAbsolutePath());
            });
        });
    }

    private ApiServerExtension registerExtension(Project project) {
        ApiServerExtension extension = project.getExtensions().create(ApiServerExtension.EXTENSION_NAME, ApiServerExtension.class);
        // Configure the extension with some defaults
        extension.getHost().convention(ApiServer.DEFAULT_HOST);
        extension.getPort().convention(ApiServer.DEFAULT_PORT);
        extension.getScheme().convention(ApiServer.DEFAULT_SCHEME);
        extension.getContextPath().convention(ApiServer.DEFAULT_CONTEXT_PATH);
        extension.getWaitSecondsAfterStart().convention(APISERVER_DEFAULT_WAIT_SECONDS);
        extension.getEnvironment().convention(System.getenv());
        extension.getSystemProperties().convention(System.getProperties().entrySet().stream()
            .collect(java.util.stream.Collectors.toMap(
                e -> String.valueOf(e.getKey()),
                e -> String.valueOf(e.getValue())
            )));
        extension.getArguments().convention(java.util.Collections.emptyList());
        return extension;
    }

    private URI baseUri(ApiServerExtension extension) {
        try{
            return new URI(String.format("%s://%s:%d/%s",
                extension.getScheme().get(),
                extension.getHost().get(),
                extension.getPort().get(),
                extension.getContextPath().get()));
        } catch (Exception e) {
            throw new RuntimeException("Failed to build API server URI", e);
        }
    }
    //private File resolveJarFile(Project project, String configurationName) {
    //    return project.getConfigurations().getByName(configurationName).getSingleFile();
    //}
}
