plugins {
    id 'geoclient.library-conventions'
    id 'geoclient.test-conventions'
    id 'geoclient.jni-native-conventions'
}

// Exclude from spotless (gradle plugin) license header check because of custom header.
spotless.java {
    targetExclude 'src/main/java/gov/nyc/doitt/gis/geoclient/jni/util/NativeLibraryLocator.java'
}
