apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    release-scope: pvc-only
  name: pvc-geosupport
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
