== Geosupport Documentation

This section provides notes on how Geoclient interacts with the Geosupport function API. This section also provides links to the Department of City Planning's documentation for Geosupport.

{dcp-upg}[Geosupport System - Universal Programming Guide (UPG)] is the official, authoritative reference for Geosupport.

'''

[#geosupport-return-codes]
=== Geosupport Return Codes

As a developer using Geoclient to geocode New York City locations, it is important to understand how Geosupport handles warnings and errors. Geosupport functions return a variety of codes, reasons, and messages that indicate the success or failure of a request. These codes are essential for diagnosing issues with your geocoding requests.

Geosupport return codes can be categorized as follows:

.Geosupport Return Codes
[cols="2a,2a,2",options="header"]
|===
|Return Code
|Description
|Response Fields

|`00`
|Success
|`geosupportReturnCode`, (`reasonCode` and `message` will be *blank*)

|`01`
|Success with warnings
|`geosupportReturnCode`, `reasonCode`, `message`

|GRC greater than `01`
|Reject or error
|`geosupportReturnCode`, `reasonCode`, `message`
|===

Some Geosupport functions are actually just the combined results of two "sub-function" calls.
At this time, function `1B` (exposed by the Geoclient `/address` endpoint) is the only case where this applies.

Results returned by function `1B` are composed of calls to functions `1EX`(theoretical address that may or may not exist in reality computed using the house number range based off of segment information from the street's centerline) and `1AX` (real address and associated property-level information based on tax lot information).

*Function 1B*

Although it is uncommon, there are a significant number of locations where data is valid and/or available for only one of these two sub-function calls. Therefore, please check the following fields when calling Geoclient's `address` endpoint:

.Function B Sub-functions
[cols="2a,2a,1a"]
|===
|1B Sub-function
|Field
|Alias

|`1EX`
|`geosupportReturnCode`
|`returnCode1e`

|`1EX`
|`reasonCode`
|`reasonCode1e`

|`1EX`
|`message`
|

|`1AX`
|`geosupportReturnCode2`
|`returnCode1a`

|`1AX`
|`reasonCode2`
|`reasonCode1a`

|`1AX`
|`message2`
|
|===

This section coved only the most basic meaning of Geosupport return codes. In practice, effective geocoding with Geosupport often requires referencing the detailed documentation provided by the Department of City Planning directly.

The following resources are invaluable for understanding the full range of return codes, reasons, and messages that Geosupport may produce:

* {dcp-upg}/appendices/appendix04/[Geosupport Return Codes, Reasons Codes and Messages] summarizes return codes, reason codes, and messages. 
* {dcp-upg}/chapters/chapterII/section02/[Geosupport Return Codes and Reject Handling] provides a detailed overview of how Geosupport handles errors and returns codes.

Although sometimes cryptic or highly specifc, knowing where to look for these codes and how to interpret them can save you time and effort when troubleshooting geocoding issues.

=== Support for Geosupport Street Codes
 
A short, high-level overview of Geosupport street code handling is available in the `Street (Name / Code)` section on this {dcp-goat}/UserGuide[page]. This provides a great introduction but doesn't go into enough detail if you need to understand the differences between primary, principal, and preferred street names. For advanced use-cases, DCP provides the (_drum roll please..._) {dcp-upg}[*Geosupport System User Programming Guide*].

Geosupport's street-related functions (i.e., functions `D`, `DG`, `DN`) are covered in full detail in the following chapters:

* {dcp-upg}/chapters/chapterIII/chapterIII/[Chapter III: Street Name Processing]
* {dcp-upg}/chapters/chapterIV/chapterIV/[Chapter IV: Street Codes]

For working with the `/normalize` endpoint, the reading following sections is probably enough to get you started:

* {dcp-upg}/chapters/chapterIII/section01/[Section 3.1]
* {dcp-upg}/chapters/chapterIII/section02/[Section 3.2]
* {dcp-upg}/chapters/chapterIII/section03/[Section 3.3]

For example, the address "2019 7th Avenue, Manhattan" is north of Central Park. In this location, a more "appropriate" name for 7th Avenue is (as reflected by street signs) "Adam Clayton Powell JR Boulevard" although both are considered valid.

.Geosupport `streetcode` functions 
[cols="1a,1a,1a,1a,3a"]
|===
| Input | Geosupport Function | Name Returned | Example Code | Example Name

| `B5SC`
| `D`
| Primary street name
| 110610
| 7 AVENUE

| `B7SC`
| `DG`
| Principle street name
| 11061001
| ADAM CLAYTON POWELL JR BOULEVARD

| `B10SC`
| `DN`
| Principle street name
| 11061001100
| ADAM CLAYTON POWELL JR BOULEVARD
|===

See <<street-code-b5sc,`/streetcode/b5sc`>> and <<street-code,`/streetcode`>> for the requests and responses used in this example.

[NOTE]
====
Some Geosupport geocoding functions (e.g., functions `1E` and `1B`) return a "BOE preferred street name" which is the name for the street that the Board of Elections uses for the address of voting sites. This is different than the "primary", "principle", and "preferred" street names returned by functions `D`, `DG`, `DN`.
====

For detailed information on Geosupport streetcodes and the differences between primary, principle, and preferred street names, see the following documentation:

* {dcp-upg}/chapters/chapterIV/section01/[Introduction: Street Codes and Geographic Retrieval Consistency]
* {dcp-upg}/chapters/chapterIV/section06/[Functions D, DG and DN; Primary, Principal and Preferred Street Names]
