== REST API

This section documents how to call the Geoclient REST API and provides example requests and responses.

'''

The Geoclient service provides the following endpoints:

.Endpoints
[cols="1,2,1"]
|===
|Type | Description | Geosupport Function

|Address
|Given a valid address, provides blockface-level, property-level, and political information ({dcp-goat}/Function1B[source]).
|1B{empty}footnote:1B[See {dcp-upg-cows}#work-area-2-cow-function-1b[1B]]

|Address Point
|"Function AP finds the address point for a given address. Address points are point locations located approximately five feet inside the building along the corresponding street frontage. Address points do not exist for all administrative address ranges assigned to a building, but usually only reflect the posted address." ({dcp-goat}/FunctionAP[source])
|AP{empty}footnote:AP[See {dcp-upg-cows}#work-area-2-cow-function-ap[AP]]

|BBL
|Given a valid borough, block, and lot provides property-level information. ({dcp-goat}/FunctionBL[source])
|BL{empty}footnote:BL[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BL]]

|BIN
|Given a valid building identification number provides property-level information. ({dcp-goat}/FunctionBN[source])
|BN{empty}footnote:BN[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BN]]

|Blockface
|Given a valid borough, "on street" and cross streets provides blockface-level information. ({dcp-goat}/Function3[source])
|3{empty}footnote:3[See {dcp-upg-cows}#work-area-2-cow-function-3[3]], 3X{empty}footnote:3X[See {dcp-upg-cows}#work-area-2-cow-function-3-extended[3X]]

|Intersection
|Given a valid borough and cross streets returns information for the point defined by the two streets. ({dcp-goat}/Function2[source])
|2{empty}footnote:2[See {dcp-upg-cows}#work-area-2-cow-function-2[2]], 2W{empty}footnote:2W[See {dcp-upg-cows}#work-area-2-cow-function-2w-wide[2W]]

|Place
|Same as 'Address' above using well-known NYC place name for input (instead of a house number and street).
|1B{empty}footnote:1B[]

|Search
|Provides parsing and search algorithm customization for several of the other endpoints listed in this section. Typically used for geocoding unstructured text to support "single-field" user searches. See the <<Search>> section below for details.
|Address, BBL, BIN, Blockface, Intersection, Place

|Streetcode
|Translates a Geosupport street code (`B5SC`, `B7SC`, or `B10SC`) to a street name and `B10SC`. ({dcp-goat}/FunctionD[source])
|D,DG,DN{empty}footnote:D-DG-DN[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[D, DG, DN]]

|Normalize
|Normalizes a street name but does *not* verify that it actually exists. ({dcp-goat}/FunctionN[source])
|N{empty}footnote:N[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[N]]

|Version
|Provides software version information about the Geoclient endpoint itself and Geosupport version/release info directly from the Geosupport instance this endpoint is currently using.
|HR (undocumented Geosupport metadata function)
|===

[#calling-the-geoclient-api]
=== Calling the Geoclient API

==== Requests

All requests are made as simple `HTTP GET` requests with input arguments specified as URL query string and/or request parameters. The service returns the `JSON` (`application/json`) media type by default unless a `Content-Type` header or the `.xml` file extension is appended as a request parameter to the endpoint function.

----
/search?input=100%20centre%20street%20manhattan <1>

/search.json?input=100%20centre%20street%20manhattan <2>
       ^^^^^

/search.xml?input=100%20centre%20street%20manhattan <3>
       ^^^^
----
<1> Returns `application/json` (default)
<2> Returns `application/json`
<3> Returns `application/xml`

WARNING: In the example above, (2) and (3) use file extensions as request (path) parameters. This functionality is deprecated and will eventually be removed from Geoclient. In future versions, use of the `Content-Type` header will be the way to request a non-default media type.

==== Responses

Any response from Geoclient is composed almost entirely from the results of the proxied Geosupport function call. This documentation no longer attempts to provide in-depth information about these functions. Instead, links are provided to the Department of City Planning's detailed documentation about their geocoding logic and return data.

Here's some high-level guidelines that will allow your code to remain loosely coupled with this API:

* By default, Geoclient does not serialize fields returned from Geosupport with NULL values in order to reduce unecessary network I/O.
The responses shown below are for example purposes only and do not include all possible fields that may be returned.
* Even for successfully recognized input, certain data attributes may not be available for some locations. Similarly, some attributes only make sense for certain input types.
* Although the examples are "pretty-printed" in this document, calling applications should not depend on any particular formatting of responses.
* The order of returned data elements is unspecified.
* Client code which parses the structured text of a Geoclient response should not rely upon significant whitespace or element/attribute ordering.
* _However_, the field values returned by Geosupport **__sometimes do contain significant whitespace or formatting__** which Geoclient _intentionally_ leaves unchanged.
* Occasionally, Geosupport fails to recognize a valid location or there is a bug in the Geoclient code. See Section FIXME for information on when and how to contact the appropriate team.

[#auth]
=== Authentication/Authorization

Geoclient does not perform any kind of authentication or authorization. However, most hosted instances of the service run behind some kind API gateway that requires access credentials.

.Historical documentation of access API's
****
Previous versions of this document described accessing protected Geoclient servers that were hosted by the City of New York. However, since that time, more hosted endpoints using different authentication schemes have become available.

Although it is beyond the scope of this document, here's a brief summary of access methods still in use at this time:

* API authorization provided as:
** `HTTP` header:
*** `Ocp-Apim-Subscription-Key`
** `HTTP` query string parameters:
*** `app_id`
*** `app_key`

Contact your provider for signup and access instructions.
****

[#common-request]
=== Common query string and request parameters

The following request parameters are required for all operations (except where noted):

.Case sensitivity
****

The Geoclient base URI and query parameter names *_are case-sensitive_*!
....
# valid
/geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
....
....
# invalid
/Geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
 ^
/geoclient/v2/address?houseNumber=2826&Street=broadway&borough=manhattan
                                       ^
....
However, parameter _values_ are *not* case-sensitive.
....
# valid
/geoclient/v2/address?houseNumber=2826&street=BROADWAY&borough=Manhattan
                               These are ok:  ^^^^^^^^         ^
....
****

==== Borough

The `borough` parameter can either be a borough name or a borough number. Borough names are *not* case-sensitive.

.Valid Values
[cols="2,2a,1"]
|===
|Borough |By name |By number
|Manhattan
| * `Manhattan`
  * `MN`
|`1`

|Bronx
| * `Bronx`
  * `BX`
  * `The Bronx`
|`2`

|Brooklyn
| * `Brooklyn`
  * `BK`
  * `BKLYN`
|`3`

|Queens
| * `Queens`
  * `QN`
|`4`

|Staten Island
| * `Staten Island`
  * `SI`
  * `STATENISLAND`
  * `STATENIS`
|`5`
|===

The preceeding table describes borough values recognized by Geosupport. The Geoclient `/search` endpoint some additional aliases to improve the parsing of single-field searches.

Recognized as `Manhattan`:

....
`NEW YORK`
`NEW YORK CITY`
`N.Y.C.`
`NYC`
`N.Y.`
`NY`
....

Recognized as `Queens`:

....
Arverne
Astoria
Bayside
Bellerose
Breezy Point
Cambria Heights
College Point
Corona
East Elmhurst
Elmhurst
Far Rockaway
Floral Park
Flushing
Forest Hills
Fresh Meadows
Glen Oaks
Hollis
Howard Beach
Inwood
Jackson Heights
Jamaica
Kew Gardens
Little Neck
Long Island City
Maspeth
Middle Village
New Hyde Park
Oakland Gardens
Ozone Park
Qs
Queens Village
Rego Park
Richmond Hill
Ridgewood
Rockaway Park
Rosedale
Saint Albans
South Ozone Park
South Richmond Hill
Springfield Gardens
Sunnyside
Whitestone
Woodhaven
Woodside
....

=== Understanding Geoclient Response Status

There are two ways in which the Geoclient service communicates call status information: `HTTP` status codes and Geosupport return codes.

==== HTTP Status Codes

Clients calling the service will always receive an `HTTP` status code, either from the service or (e.g., if a connection cannot be made) from the `HTTP` protocol implementation itself.

Full documentation of possible `HTTP` status codes are beyond the scope of this document, but {mozilla-http-status-codes}[Mozilla] provides an easy to understand reference site. For more detailed information, please see section 15 of {ietf-rfc-9110-status-codes}[RFC 9110].

In brief, here are the most commonly returned `HTTP` status codes:

.Common HTTP Status Codes
[cols="1a,2a"]
|===
|HTTP Status Code
|Meaning

|`200`
|The call successfully reached the Geoclient application (See <<geosupport-return-codes>> for the status of the actual geocoding attempt).

|`400`
|A required query parameter is missing. See for information on call parameters.

|`401`
|Unauthorized: indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

|`403`
|Forbidden: The `HTTP` 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.

|`404`
|An incorrect URL has been used. There is no service mapped to it.

|`500`
|The Geoclient service could not process the request due to an internal server error.
|===

[#geosupport-return-codes]
==== Geosupport Return Codes

The Geosupport application uses return codes, reason codes, and messages to indicate the processing status of a given function call.

NOTE: Return codes come directly from the Geosupport application; as mentioned above, the Geoclient service uses standard `HTTP` status codes to report on it's own request processing.

These return codes are often highly specific to a given function or processing state and there are many of them. This section describes only a very high-level summary of their meaning.

Please see DCP's official {dcp-upg}/appendices/appendix04/[return code documentation] for a complete explanation.

The following table summarizes the meaning of the codes returned by

.Geosupport Return Codes
[cols="2a,2a,2"]
|===
|Return Code
|Description
|Response Fields

|`00`
|Success
|`geosupportReturnCode`, (`reasonCode` and `message` will be *blank*)

|`01`
|Success with warnings
|`geosupportReturnCode`, `reasonCode`, `message`

|GRC greater than `01`
|Reject or error
|`geosupportReturnCode`, `reasonCode`, `message`
|===

Some Geosupport functions are actually just the combined results of two "sub-function" calls.
At this time, function `1B` (exposed by the Geoclient `/address` endpoint) is the only case where this applies.

Results returned by function `1B` are composed of calls to functions `1EX`(theoretical address that may or may not exist in reality computed using the house number range based off of segment information from the street's centerline) and `1AX` (real address and associated property-level information based on tax lot information).

*Function 1B*

Although it is uncommon, there are a significant number of locations where data is valid and/or available for only one of these two sub-function calls. Therefore, please check the following fields when calling Geoclient's `address` endpoint:

.Function B Sub-functions
[cols="2a,2a,1a"]
|===
|1B Sub-function
|Field
|Alias

|`1EX`
|`geosupportReturnCode`
|`returnCode1e`

|`1EX`
|`reasonCode`
|`reasonCode1e`

|`1EX`
|`message`
|

|`1AX`
|`geosupportReturnCode2`
|`returnCode1a`

|`1AX`
|`reasonCode2`
|`reasonCode1a`

|`1AX`
|`message2`
|
|===

=== Endpoints

==== Address

*Path:* `/v2/address`

*Parameters:*

|===
| Parameter Name | Required/Optional | Comments

| `houseNumber`
| required
| House number of the address.

| `street`
| required
| Street name or 7-digit street code.

| `borough`
| required if `zip` is not given
| Valid values defined in <<Borough>>.

| `zip`
| required if `borough` is not given
| Standard USPS 5-digit zip code or zip+4 (see {wikipedia-zip-code}[this article]).  Must be a valid zip code for an area within New York City limits.
|===

*Example Requests:*

Request:

....
/geoclient/v2/address?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/address-1.jsonc[tags=user_guide]
----
====

==== Address Point

*Path:* `/v2/addresspoint`

*Parameters:*

Same as the <<Address>> endpoint.

Request:

....
/geoclient/v2/addresspoint?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/addresspoint-1.jsonc[tags=user_guide]
----
====

==== BBL

*Path:* `/v2/bbl`

*Parameters:*


Request:

....
/geoclient/v2/bbl?borough=manhattan&block=67&lot=1
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/bbl-1.jsonc[tags=user_guide]
----
====

==== BIN

Request:

....
/geoclient/v2/bin?bin=1079043
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/bin-1.jsonc[tags=user_guide]
----
====

==== Blockface

Request:

....
/geoclient/v2/blockface?onStreet=broadway&crossStreetOne=w%20100%20st&crossStreetTwo=w%20101%st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/blockface-1.jsonc[tags=user_guide]
----
====

==== Intersection

Request:

....
/geoclient/v2/intersection?crossStreetOne=broadway&crossStreetOne=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/intersection-1.jsonc[tags=user_guide]
----
====

==== Search

Request:

....
/geoclient/v2/search?input=314%20w%20100%20st%20manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/search-1.jsonc[tags=user_guide]
----
====

==== Version

Request:

....
/geoclient/v2/version.json
....

Response:

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/version-1.jsonc[tags=user_guide]
----
====