== REST API

This section documents how to call the Geoclient REST API and provides example requests and responses.

'''

The Geoclient service provides the following endpoints:

.Endpoints
[cols="1,2,1"]
|===
|Type |Description |Geosupport Function

|Address
|Given a valid address, provides blockface-level, property-level, and political information ({dcp-goat}/Function1B[source]).
|1B{empty}footnote:1B[See {dcp-upg-cows}#work-area-2-cow-function-1b[1B]]

|Address Point
|"Function AP finds the address point for a given address. Address points are point locations located approximately five feet inside the building along the corresponding street frontage. Address points do not exist for all administrative address ranges assigned to a building, but usually only reflect the posted address." ({dcp-goat}/FunctionAP[source])
|AP{empty}footnote:AP[See {dcp-upg-cows}#work-area-2-cow-function-ap[AP]]

|BBL
|Given a valid borough, block, and lot provides property-level information. ({dcp-goat}/FunctionBL[source])
|BL{empty}footnote:BL[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BL]]

|BIN
|Given a valid building identification number provides property-level information. ({dcp-goat}/FunctionBN[source])
|BN{empty}footnote:BN[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BN]]

|Blockface
|Given a valid borough, "on street" and cross streets provides blockface-level information. ({dcp-goat}/Function3[source])
|3{empty}footnote:3[See {dcp-upg-cows}#work-area-2-cow-function-3[3]], 3X{empty}footnote:3X[See {dcp-upg-cows}#work-area-2-cow-function-3-extended[3X]]

|Intersection
|Given a valid borough and cross streets returns information for the point defined by the two streets. ({dcp-goat}/Function2[source])
|2{empty}footnote:2[See {dcp-upg-cows}#work-area-2-cow-function-2[2]], 2W{empty}footnote:2W[See {dcp-upg-cows}#work-area-2-cow-function-2w-wide[2W]]

|Place
|Same as 'Address' above using well-known NYC place name for input (instead of a house number and street).
|1B{empty}footnote:1B[]

|Search
|Provides parsing and search algorithm customization for several of the other endpoints listed in this section. Typically used for geocoding unstructured text to support "single-field" user searches. See the <<Search>> section below for details.
|Address, BBL, BIN, Blockface, Intersection, Place

|Streetcode
|Translates a Geosupport street code (`B5SC`, `B7SC`, or `B10SC`) to a street name and `B10SC`. ({dcp-goat}/FunctionD[source])
|D,DG,DN{empty}footnote:D-DG-DN[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[D, DG, DN]]

|Normalize
|Normalizes a street name but does *not* verify that it actually exists. ({dcp-goat}/FunctionN[source])
|N{empty}footnote:N[See {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[N]]

|Version
|Provides software version information about the Geoclient endpoint itself and Geosupport version/release info directly from the Geosupport instance this endpoint is currently using.
|HR (undocumented Geosupport metadata function)
|===

[#calling-the-geoclient-api]
=== Calling the Geoclient API

==== Requests

All requests are made as simple `HTTP GET` requests with input arguments specified as URL query string and/or request parameters. The service returns the `JSON` (`application/json`) media type by default unless a `Content-Type` header or the `.xml` file extension is appended as a request parameter to the endpoint function.

----
/search?input=100%20centre%20street%20manhattan <1>

/search.json?input=100%20centre%20street%20manhattan <2>
       ^^^^^

/search.xml?input=100%20centre%20street%20manhattan <3>
       ^^^^
----
<1> Returns `application/json` (default)
<2> Returns `application/json`
<3> Returns `application/xml`

WARNING: In the example above, (2) and (3) use file extensions as request (path) parameters. This functionality is deprecated and will eventually be removed from Geoclient. In future versions, use of the `Content-Type` header will be the way to request a non-default media type.

==== Responses

Any response from Geoclient is composed almost entirely from the results of the proxied Geosupport function call. This documentation no longer attempts to provide in-depth information about these functions. Instead, links are provided to the Department of City Planning's detailed documentation about their geocoding logic and return data.

Here's some high-level guidelines that will allow your code to remain loosely coupled with this API:

* By default, Geoclient does not serialize fields returned from Geosupport with NULL values in order to reduce unecessary network I/O.
The responses shown below are for example purposes only and do not include all possible fields that may be returned.
* Even for successfully recognized input, certain data attributes may not be available for some locations. Similarly, some attributes only make sense for certain input types.
* Although the examples are "pretty-printed" in this document, calling applications should not depend on any particular formatting of responses.
* The order of returned data elements is unspecified.
* Client code which parses the structured text of a Geoclient response should not rely upon significant whitespace or element/attribute ordering.
* _However_, the field values returned by Geosupport **__sometimes do contain significant whitespace or formatting__** which Geoclient _intentionally_ leaves unchanged.
* Occasionally, Geosupport fails to recognize a valid location or there is a bug in the Geoclient code. See Section FIXME for information on when and how to contact the appropriate team.

[#auth]
=== Authentication/Authorization

Geoclient does not perform any kind of authentication or authorization. However, most hosted instances of the service run behind some kind API gateway that requires access credentials.

.Historical documentation of access API's
****
Previous versions of this document described accessing protected Geoclient servers that were hosted by the City of New York. However, since that time, more hosted endpoints using different authentication schemes have become available.

Although it is beyond the scope of this document, here's a brief summary of access methods still in use at this time:

* API authorization provided as:
** `HTTP` header:
*** `Ocp-Apim-Subscription-Key`
** `HTTP` query string parameters:
*** `app_id`
*** `app_key`

Contact your provider for signup and access instructions.
****

[#common-request]
=== Common query string and request parameters

The following request parameters are required for all operations (except where noted):

.Case sensitivity
****

The Geoclient base URI and query parameter names *_are case-sensitive_*!
....
# valid
/geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
....
....
# invalid
/Geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
 ^
/geoclient/v2/address?houseNumber=2826&Street=broadway&borough=manhattan
                                       ^
....
However, parameter _values_ are *not* case-sensitive.
....
# valid
/geoclient/v2/address?houseNumber=2826&street=BROADWAY&borough=Manhattan
                               These are ok:  ^^^^^^^^         ^
....
****

==== Borough

The `borough` parameter can either be a borough name or a borough number. Borough names are *not* case-sensitive.

.Valid Values
[cols="2,2a,1"]
|===
|Borough |By name |By number
|Manhattan
| * `Manhattan`
  * `MN`
|`1`

|Bronx
| * `Bronx`
  * `BX`
  * `The Bronx`
|`2`

|Brooklyn
| * `Brooklyn`
  * `BK`
  * `BKLYN`
|`3`

|Queens
| * `Queens`
  * `QN`
|`4`

|Staten Island
| * `Staten Island`
  * `SI`
  * `STATENISLAND`
  * `STATENIS`
|`5`
|===

The preceeding table describes borough values recognized by Geosupport. The Geoclient `/search` endpoint some additional aliases to improve the parsing of single-field searches.

Recognized as `Manhattan`:

....
`NEW YORK`
`NEW YORK CITY`
`N.Y.C.`
`NYC`
`N.Y.`
`NY`
....

Recognized as `Queens`:

....
Arverne
Astoria
Bayside
Bellerose
Breezy Point
Cambria Heights
College Point
Corona
East Elmhurst
Elmhurst
Far Rockaway
Floral Park
Flushing
Forest Hills
Fresh Meadows
Glen Oaks
Hollis
Howard Beach
Inwood
Jackson Heights
Jamaica
Kew Gardens
Little Neck
Long Island City
Maspeth
Middle Village
New Hyde Park
Oakland Gardens
Ozone Park
Qs
Queens Village
Rego Park
Richmond Hill
Ridgewood
Rockaway Park
Rosedale
Saint Albans
South Ozone Park
South Richmond Hill
Springfield Gardens
Sunnyside
Whitestone
Woodhaven
Woodside
....

=== Understanding Geoclient Response Status

There are two ways in which the Geoclient service communicates call status information: `HTTP` status codes and Geosupport return codes.

==== HTTP Status Codes

Clients calling the service will always receive an `HTTP` status code, either from the service or (e.g., if a connection cannot be made) from the `HTTP` protocol implementation itself.

Full documentation of possible `HTTP` status codes are beyond the scope of this document, but {mozilla-http-status-codes}[Mozilla] provides an easy to understand reference site. For more detailed information, please see section 15 of {ietf-rfc-9110-status-codes}[RFC 9110].

In brief, here are the most commonly returned `HTTP` status codes:

.Common HTTP Status Codes
[cols="1a,2a"]
|===
|HTTP Status Code
|Meaning

|`200`
|The call successfully reached the Geoclient application (See <<geosupport-return-codes>> for the status of the actual geocoding attempt).

|`400`
|A required query parameter is missing. See for information on call parameters.

|`401`
|Unauthorized: indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

|`403`
|Forbidden: The `HTTP` 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.

|`404`
|An incorrect URL has been used. There is no service mapped to it.

|`500`
|The Geoclient service could not process the request due to an internal server error.
|===

[#geosupport-return-codes]
==== Geosupport Return Codes

The Geosupport application uses return codes, reason codes, and messages to indicate the processing status of a given function call.

NOTE: Return codes come directly from the Geosupport application; as mentioned above, the Geoclient service uses standard `HTTP` status codes to report on it's own request processing.

These return codes are often highly specific to a given function or processing state and there are many of them. This section describes only a very high-level summary of their meaning.

Please see DCP's official {dcp-upg}/appendices/appendix04/[return code documentation] for a complete explanation.

The following table summarizes the meaning of the codes returned by

.Geosupport Return Codes
[cols="2a,2a,2"]
|===
|Return Code
|Description
|Response Fields

|`00`
|Success
|`geosupportReturnCode`, (`reasonCode` and `message` will be *blank*)

|`01`
|Success with warnings
|`geosupportReturnCode`, `reasonCode`, `message`

|GRC greater than `01`
|Reject or error
|`geosupportReturnCode`, `reasonCode`, `message`
|===

Some Geosupport functions are actually just the combined results of two "sub-function" calls.
At this time, function `1B` (exposed by the Geoclient `/address` endpoint) is the only case where this applies.

Results returned by function `1B` are composed of calls to functions `1EX`(theoretical address that may or may not exist in reality computed using the house number range based off of segment information from the street's centerline) and `1AX` (real address and associated property-level information based on tax lot information).

*Function 1B*

Although it is uncommon, there are a significant number of locations where data is valid and/or available for only one of these two sub-function calls. Therefore, please check the following fields when calling Geoclient's `address` endpoint:

.Function B Sub-functions
[cols="2a,2a,1a"]
|===
|1B Sub-function
|Field
|Alias

|`1EX`
|`geosupportReturnCode`
|`returnCode1e`

|`1EX`
|`reasonCode`
|`reasonCode1e`

|`1EX`
|`message`
|

|`1AX`
|`geosupportReturnCode2`
|`returnCode1a`

|`1AX`
|`reasonCode2`
|`reasonCode1a`

|`1AX`
|`message2`
|
|===

=== Endpoints

==== Address

*Path:* `/v2/address`

*Parameters:*

.`/address` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`houseNumber`
|required
|House number of the address.

|`street`
|required
|Street name or 7-digit street code.

|`borough`
|required if `zip` is not given
|Valid values defined in <<Borough>>.

|`zip`
|required if `borough` is not given
|Standard USPS 5-digit zip code or zip+4 (see {wikipedia-zip-code}[this article]).  Must be a valid zip code for an area within New York City limits.
|===

*Example Requests:*

Request:

....
/geoclient/v2/address?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/address-1.jsonc[tags=user_guide]
----
====

==== Address Point

*Path:* `/v2/addresspoint`

*Parameters:*

Same as the <<Address>> endpoint.

*Example Requests:*

Request:

....
/geoclient/v2/addresspoint?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/addresspoint-1.jsonc[tags=user_guide]
----
====

==== BBL

*Path:* `/v2/bbl`

*Parameters:*

.`/bbl` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments
|`borough`
|required
|Valid values defined in <<Borough>>.

|`block`
|required
|Tax block. Zero padding is not required.

|`lot`
|required
|Tax lot. Zero padding is not required.
|===

*Example Requests:*

Request:

....
/geoclient/v2/bbl?borough=manhattan&block=67&lot=1
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/bbl-1.jsonc[tags=user_guide]
----
====

==== BIN

*Path:* `/v2/bin`

*Parameters:*

.`/bin` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`bin`
|required
|Building identification number.
|===

*Example Requests:*

Request:

....
/geoclient/v2/bin?bin=1079043
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/bin-1.jsonc[tags=user_guide]
----
====

==== Blockface

*Path:* `/v2/blockface`

*Parameters:*

.`/blockface` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`onStreet`
|required
|Name of the street between the two cross streets.

|`crossStreetOne`
|required
|First cross street of blockface.

|`crossStreetTwo`
|required
|Second cross street of blockface.

|`borough`
|required
|Borough of `onStreet`. Valid values defined in <<Borough>>.

|`boroughCrossStreetOne`
|optional
|Borough of first cross street. Defaults to value of `borough` parameter if not supplied.

|`boroughCrossStreetTwo`
|optional
|Borough of second cross street. Defaults to value of `borough` parameter if not supplied.

|`compassDirection`
|optional
|Used to request information about only one side of the street. Valid values are: `N`, `S`, `E`, or `W`.
|===

*Example Requests:*

Request:

....
/geoclient/v2/blockface?onStreet=broadway&crossStreetOne=w%20100%20st&crossStreetTwo=w%20101%st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/blockface-1.jsonc[tags=user_guide]
----
====

==== Intersection

*Path:* `/v2/blockface`

*Parameters:*

.`/intersection` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`crossStreetOne`
|required
|First cross street of the intersection.

|`crossStreetTwo`
|required
|Second cross street of the intersection.

|`borough`
|required
|Borough of first cross street or of both cross streets if no other borough parameter is supplied. Valid values defined in <<Borough>>.

|`boroughCrossStreetTwo`
|optional
|Borough of second cross street. If not supplied, assumed to be same as `borough` parameter.

|`compassDirection`
|optional
|Optional for most requests.	Required only if the cross streets intersect more than once. Valid values are: `N`, `S`, `E` or `W`.
|===

*Example Requests:*

Request:

....
/geoclient/v2/intersection?crossStreetOne=broadway&crossStreetOne=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/intersection-1.jsonc[tags=user_guide]
----
====

==== Normalize

*Path:* `/v2/normalize`

*Parameters:*

.`/normalize` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`name`
|required
|Street name to normalize. Note that no validation is done to verify if this is a valid NYC street.

|`length`
|optional
|If not given, defaults to `32`.

|`format`
|optional
|If not given, defaults to `S`.
|===

*Example Requests:*

Request:

....
/geoclient/v2/name?name=east%20158th%20Street
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/normalize-1.jsonc[tags=user_guide]
----
====

==== Place

*Path:* `/v2/place`

*Parameters:*

.`/place` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`name`
|required
|Well-known place name.

|`borough`
|required if `zip` is not given
|Valid values defined in <<Borough>>.

|`zip`
|required if `borough` is not given
|Standard USPS 5-digit zip code or zip+4 (see {wikipedia-zip-code}[this article]).  Must be a valid zip code for an area within New York City limits.
|===

*Example Requests:*

Request:

....
/geoclient/v2/address?houseNumber=314&street=w%20100%20st&borough=manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/address-1.jsonc[tags=user_guide]
----
====

.`/place` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments
|===

==== Search

The `/search` endpoint provides a way to search for an address, BBL, BIN, blockface, or place using a single unparsed location string. Assuming that the Geoclient parser can guess the location type requested and the given single-field input parameter contains contains enough information to generate a successful Geosupport call, the service will return one or more sets of geocodes corresponding to the type of request that was made.

The single-field search will attempt to recognize the type of request being made using the following (simplified) parsing strategies which are listed in the order they are executed:

. A ten-digit number where the first digit is `1`, `2`, `3`, `4` or `5` is recognized as a BBL request:

  1000670001

. A seven-digit number where the first digit is `1`, `2`, `3`, `4` or `5` is recognized as a BIN request:

  1079043

. If the input string ends with a United States-related country identifier it is recognized and removed and discarded:

  314 W 100 ST, NY, NY 10025 [USA]

. If the input string ends with a five or seven-digit zipcode it is removed and kept as a `<ZIP>` token:

  314 W 100 ST, NY, NY [10025]

. If the input string ends with a valid two-character U.S. state abreviation it is recognized and removed:

  314 W 100 ST, NY, [NY]

NOTE: Input ending in only a single instance of `NY` or `New York` (case-insensitive) is treated as a city name alias for Manhattan and not the state of New York.

. If the input string ends with a known NYC city name it is removed and kept as a `<CITY_NAME>` token:

  93-02 69th Ave, [Forest Hills]

. If the input string ends with a known borough name or abreviation it is removed and kept as a `<BOROUGH_NAME>` token:

  80 Monroe Ave [SI]

. A BLOCKFACE request is identified using the pattern `<ON_STREET>` `between` `<CROSS_STREET_ONE>` `and` `<CROSS_STREET_TWO>`:

  [Broadway] between [W 100 St] and [W 101 St]

. An INTERSECTION request is identified using the pattern `<CROSS_STREET_ONE>` `and` `<CROSS_STREET_TWO>`:

  [Broadway] and [W 100 St]

. If the input string starts with a known house number format, it is recognized and kept as `<BASIC_HOUSE_NUMBER>` and (optionally) `<HOUSE_NUMBER_SUFFIX>` token(s):

  [93-02] 69th Ave

. Any remaining input is treated as an input street. If a `<BASIC_HOUSE_NUMBER>` token has been parsed, the input is recognized as an ADDRESS request, otherwise it is defaulted to a PLACE request

All matching is case-insensitive. Leading/trailing whitespace and any punctuation characters are ignored.

After the input has been parsed into tokens and the request type has been determined, the service resolves the BOROUGH_NAME and/or CITY_NAME token(s) into a New York City borough code (`1`=`Manhattan`, `2`=`Bronx`, `3`=`Brooklyn`, `4`=`Queens`, `5`=`Staten` Island).

If a valid borough code has been resolved, a single request is made to Geosupport using the specified borough code. The request is assigned a "level" of zero.

If a valid borough code cannot be derived (either because no borough was provided or the provided borough/city name is not recognized), five requests are automatically submitted - one for each borough. Each request is assigned a "level" of one.

The Geoclient service uses the concept of search levels to classify the degree to which any user input has been modified by the program before making the request to Geosupport. Roughly speaking, each additional level indicates a round of sub-searches undertaken when the service does not find an exact match.

*Path:* `/v2/search`

*Parameters:*

.`/search` arguments
[cols="1a,1a,2a"]
|===
|Parameter Name |Required/Optional |Comments

|`input`
|required
|Unparsed location input.

|`exactMatchForSingleSuccess`
|optional
|Whether a search returning only one possible successfully geocoded location is considered an exact match. Defaults to false.

|`exactMatchMaxLevel`
|optional
|The maximum number of sub-search levels to perform if Geosupport rejects the input but suggests alternative street names, etc. Defaults to 3. Maximum is allowable value is 6.

|`returnPolicy`
|optional
|Whether to return information on the search policy used to perform the search. Defaults to false.

|`returnPossiblesWithExact`
|optional
|Whether to also return successfully geocoded possible matches when available in addition to the exact match. Defaults to false.

|`returnRejections`
|optional
|Whether to return rejected response data from Geosupport. Defaults to false.

|`returnTokens`
|optional
|Whether to return the parsed input tokens recognized by the parser. Defaults to false.

|`similarNamesDistance`
|optional
|Maximum allowable Levenshtein distance between user input and a similar name suggestion from Geosupport. Defaults to 8. A higher number will allow more "guesses" to be made about an unrecognized street name.
|===

*Example Requests:*

Request:

....
/geoclient/v2/search?input=314%20w%20100%20st%20manhattan
....

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/search-1.jsonc[tags=user_guide]
----
====

==== Street Code

*Path:* `/v2/streetcode`

*Parameters:*



==== Version

*Path:* `/v2/version`

*Parameters:*

The `/version` endpoint does not accept any parameters.

*Example Requests:*

Request:

....
/geoclient/v2/version.json
....

Response:

.Show JSON
[%collapsible]
====
[source,json,indent=0]
----
include::../samples/version-1.jsonc[tags=user_guide]
----
====