== REST API

This section documents how to call the Geoclient REST API and provides example requests and responses.

'''

The Geoclient service provides the following endpoints:

.Endpoints
[cols="1,2,1"]
|===
|Type |Description |Geosupport Function

|Address
|Given a valid address, provides blockface-level, property-level, and political information ({dcp-goat}/Function1B[source]).
|1B{empty}footnote:1B[See {dcp-upg-cows}#work-area-2-cow-function-1b[1B]]

|Address Point
|"Function AP finds the address point for a given address. Address points are point locations located approximately five feet inside the building along the corresponding street frontage. Address points do not exist for all administrative address ranges assigned to a building, but usually only reflect the posted address." ({dcp-goat}/FunctionAP[source])
|AP{empty}footnote:AP[See {dcp-upg-cows}#work-area-2-cow-function-ap[AP]]

|BBL
|Given a valid borough, block, and lot provides property-level information. ({dcp-goat}/FunctionBL[source])
|BL{empty}footnote:BL[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BL]]

|BIN
|Given a valid building identification number provides property-level information. ({dcp-goat}/FunctionBN[source])
|BN{empty}footnote:BN[See {dcp-upg-cows}#work-area-2-cow-function-1a-bl-bn-extended[BN]]

|Blockface
|Given a valid borough, "on street" and cross streets provides blockface-level information. ({dcp-goat}/Function3[source])
|3{empty}footnote:3[See {dcp-upg-cows}#work-area-2-cow-function-3[3]], 3X{empty}footnote:3X[See {dcp-upg-cows}#work-area-2-cow-function-3-extended[3X]]

|Intersection
|Given a valid borough and cross streets returns information for the point defined by the two streets. ({dcp-goat}/Function2[source])
|2{empty}footnote:2[See {dcp-upg-cows}#work-area-2-cow-function-2[2]], 2W{empty}footnote:2W[See {dcp-upg-cows}#work-area-2-cow-function-2w-wide[2W]]

|Place
|Same as 'Address' above using well-known NYC place name for input (instead of a house number and street).
|1B{empty}footnote:1B[]

|Search
|Provides parsing and search algorithm customization for several of the other endpoints listed in this section. Typically used for geocoding unstructured text to support "single-field" user searches. See the <<Search>> section below for details.
|Address, BBL, BIN, Blockface, Intersection, Place

|Streetcode
|Translates a Geosupport street code (`B5SC`, `B7SC`, or `B10SC`) to a street name with the corresponding `B10SC`.
|See <<Geosupport Street Name Functions>>.

|Normalize
|Normalizes a street name but does *not* verify that it actually exists. ({dcp-goat}/FunctionN[source])
|See <<Geosupport Street Name Functions>>.

|Version
|Provides software version information about the Geoclient endpoint itself and Geosupport version/release info directly from the Geosupport instance this endpoint is currently using.
|HR (undocumented Geosupport metadata function)
|===

[#calling-the-geoclient-api]
=== Calling the Geoclient API

==== Requests

All requests are made as simple `HTTP GET` requests with input arguments specified as URL query string and/or request parameters. The service returns the `JSON` (`application/json`) media type by default unless a `Content-Type` header or the `.xml` file extension is appended as a request parameter to the endpoint function.

----
/search?input=100%20centre%20street%20manhattan <1>

/search.json?input=100%20centre%20street%20manhattan <2>
       ^^^^^

/search.xml?input=100%20centre%20street%20manhattan <3>
       ^^^^
----
<1> Returns `application/json` (default)
<2> Returns `application/json`
<3> Returns `application/xml`

WARNING: In the example above, (2) and (3) use file extensions as request (path) parameters. This functionality is deprecated and will eventually be removed from Geoclient. In future versions, adding a `Content-Type` header or an `HTTP` query string parameter will be the way to request a non-default media type.

==== Responses

Any response from Geoclient is composed almost entirely from the results of the proxied Geosupport function call. This documentation no longer attempts to provide in-depth information about these functions. Instead, links are provided to the Department of City Planning's detailed documentation about their geocoding logic and return data.

Here's some high-level guidelines that will allow your code to remain loosely coupled with this API:

* By default, Geoclient does not serialize fields returned from Geosupport with NULL values in order to reduce unecessary network I/O.
The responses shown below are for example purposes only and do not include all possible fields that may be returned.
* Even for successfully recognized input, certain data attributes may not be available for some locations. Similarly, some attributes only make sense for certain input types.
* Although the examples are "pretty-printed" in this document, calling applications should not depend on any particular formatting of responses.
* The order of returned data elements is unspecified.
* Client code which parses the structured text of a Geoclient response should not rely upon significant whitespace or element/attribute ordering.
* _However_, the field values returned by Geosupport **__sometimes do contain significant whitespace or formatting__** which Geoclient _intentionally_ leaves unchanged.
* Occasionally, Geosupport fails to recognize a valid location or there is a bug in the Geoclient code. See Section FIXME for information on when and how to contact the appropriate team.

[#common-request]
=== Common query string and request parameters

The following request parameters are required for all operations (except where noted):

.Case sensitivity
****

The Geoclient base URI and query parameter names *_are case-sensitive_*!
....
# valid
/geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
....
....
# invalid
/Geoclient/v2/address?houseNumber=2826&street=broadway&borough=manhattan
 ^
/geoclient/v2/address?houseNumber=2826&Street=broadway&borough=manhattan
                                       ^
....
However, parameter _values_ are *not* case-sensitive.
....
# valid
/geoclient/v2/address?houseNumber=2826&street=BROADWAY&borough=Manhattan
                               These are ok:  ^^^^^^^^         ^
....
****

==== Borough

The `borough` parameter can either be a borough name or a borough number. Borough names are *not* case-sensitive.

.Valid Values
[cols="2,2a,1a"]
|===
|Borough |By name |By number
|Manhattan
| * `Manhattan`
  * `MN`
|`1`

|Bronx
| * `Bronx`
  * `BX`
  * `The Bronx`
|`2`

|Brooklyn
| * `Brooklyn`
  * `BK`
  * `BKLYN`
|`3`

|Queens
| * `Queens`
  * `QN`
|`4`

|Staten Island
| * `Staten Island`
  * `SI`
  * `STATENISLAND`
  * `STATENIS`
|`5`
|===

The preceeding table describes borough values recognized by Geosupport. The Geoclient `/search` endpoint some additional aliases to improve the parsing of single-field searches.

Recognized as `Manhattan`:

....
`NEW YORK`
`NEW YORK CITY`
`N.Y.C.`
`NYC`
`N.Y.`
`NY`
....

Recognized as `Queens`:

....
Arverne
Astoria
Bayside
Bellerose
Breezy Point
Cambria Heights
College Point
Corona
East Elmhurst
Elmhurst
Far Rockaway
Floral Park
Flushing
Forest Hills
Fresh Meadows
Glen Oaks
Hollis
Howard Beach
Inwood
Jackson Heights
Jamaica
Kew Gardens
Little Neck
Long Island City
Maspeth
Middle Village
New Hyde Park
Oakland Gardens
Ozone Park
Qs
Queens Village
Rego Park
Richmond Hill
Ridgewood
Rockaway Park
Rosedale
Saint Albans
South Ozone Park
South Richmond Hill
Springfield Gardens
Sunnyside
Whitestone
Woodhaven
Woodside
....

=== Understanding Geoclient Response Status

There are two ways in which the Geoclient service communicates call status information: `HTTP` status codes and Geosupport return codes.

==== HTTP Status Codes

Clients calling the service will always receive an `HTTP` status code, either from the service or (e.g., if a connection cannot be made) from the `HTTP` protocol implementation itself.

Full documentation of possible `HTTP` status codes are beyond the scope of this document, but {mozilla-http-status-codes}[Mozilla] provides an easy to understand reference site. For more detailed information, please see section 15 of {ietf-rfc-9110-status-codes}[RFC 9110].

In brief, here are the most commonly returned `HTTP` status codes:

.Common HTTP Status Codes
[cols="1a,2a"]
|===
|HTTP Status Code
|Meaning

|`200`
|The call successfully reached the Geoclient application (See <<geosupport-return-codes>> for the status of the actual geocoding attempt).

|`400`
|A required query parameter is missing. See for information on call parameters.

|`401`
|Unauthorized: indicates that the request has not been applied because it lacks valid authentication credentials for the target resource.

|`403`
|Forbidden: The `HTTP` 403 Forbidden client error status response code indicates that the server understood the request but refuses to authorize it.

|`404`
|An incorrect URL has been used. There is no service mapped to it.

|`500`
|The Geoclient service could not process the request due to an internal server error.
|===

[#introduction-to-geosupport-return-codes]
==== Introduction to Geosupport Return Codes

As mentioned in the <<concepts,Concepts section>>, Geosupport is a separate application that has own logic and data. While Geoclient uses HTTP status codes to indicate the the success or failure of a REST request, Geosupport has its own API for communicating the status of a geocoding request.

[IMPORTANT]
====
If Geosupport cannot geocode a location, Geoclient will still return an `HTTP 200` status code. In other words:

- *_Geoclient considers all requests to be successful as long as the request was properly formatted and the Geosupport service was reachable_*.
- *_The actual success or failure of a geocoding request is determined by the Geosupport return codes_*.
====

Geosupport function calls return a variety of codes, reasons, and messages that indicate the success or failure of the geocoding operation.
These return codes are often highly specific to a given function or processing state and there are many of them. This section summarizes only the top-level codes.

.Summary of Geosupport Return Codes
[cols="1,1",options="header"]
|===
| Return Code | Description

| 00
| Successful request

| 01
| Successful request with warnings

| Anything else
| Unsuccessful request or error
|===

Understanding these codes is *essential* for diagnosing issues with your geocoding requests. The <<geosupport-return-codes,Geosupport Return Codes>> section provides a slightly more detailed discussion of these codes and how to interpret them. More importantly, it provides links to the Department of City Planning's official documentation for Geosupport which is the authoritative reference for all return codes, reason codes, and messages.

=== Geosupport Street Name Functions

Geosupport has a rich model for streets and provides many functions and flags to support street processing. Geoclient supports calls to functions `D`, `DG`, and `DN` and function `N` with the `/normalize` function.

with the `/streetcode` and `/streetcode/b5sc` endpoints

For historical reasons, Geoclient supports two endpoints for retrieving street names from street codes. Functionally, both endpoints are equivalent (see the table below), but they return results in different top-level JSON properties/XML elements:

* `/streetcode/b5sc` returns results in a top-level `response` property/element.
* `/streetcode` returns results in a top-level `streetcode` property/element.

Other than the top-level property/element, the two endpoints accept the same arguments and use the same logic when calling Geosupport:

* Both endpoints use different Geosupport functions based on input (see the table below).
* Both endpoints accept up to three `B5SC`, `B7SC`, and `B10SC` arguments.
* Both endpoints assume that all arguments are of the same streetcode type (`B5SC`, `B7SC`, or `B10SC`). If they are not, the returned values will reflect only one arbitrarily chosen type and the data may be invalid for any other types returned in the response.

The `/streetcode` endpoint calls different Geosupport functions depending on the type of street code given for the `streetCode`, `streetCodeTwo`, `streetCodeThree` parameters:

.`/streetcode` endpoint's use of Geosupport functions
[cols="1a,2a"]
|===
|Street Code Type
|Geosupport Function

|`B5SC`
|Function `D`

|`B7SC`
|Function `DG`

|`B10SC`
|Function `DN`
|===

The Geosupport input API used by the Geoclient `/normalize` and `/streetcode` endpoints is documented {dcp-upg-cows}#character-only-work-area-1-cow-all-functions[here].

=== Examples

For examples of calling Geoclient programmatically, see the {geoclient-examples-repo}[geoclient-examples] repository on GitHub.
