apiVersion: v1
appVersion: 20160715.0.11
description: Geoclient provides a RESTful API for calling NYC Department of City Planning's
  Geosupport geocoder.
engine: gotpl
home: https://maps.nyc.gov/geoclient/v2/doc
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
keywords:
- geocoding
- NYC
maintainers:
- email: mlipper@users.noreply.github.com
  name: mlipper
name: geoclient
sources:
- https://github.com/mlipper/geoclient
version: 20160715.0.11
