[versions]
geoclient = "2.0.3"
jacksonDatabind = "2.19.0"
junitJupiter = "5.12.2"
junitPlatformLauncher = "1.12.2"
logback = "1.5.18"
slf4J = "2.0.17"

[libraries]
geoclientCore = { module = "gov.nyc.doitt.gis.geoclient:geoclient-core", version.ref = "geoclient" }
geoclientJni = { module = "gov.nyc.doitt.gis.geoclient:geoclient-jni", version.ref = "geoclient" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logbackCore = { module = "ch.qos.logback:logback-core", version.ref = "logback" }
slf4J = { module = "org.slf4j:slf4j-api", version.ref = "slf4J" }
