plugins {
    id 'geoclient.library-conventions'
    id 'geoclient.test-conventions'
}

dependencies {
    implementation(platform(libs.spring.boot.dependencies))
    implementation(libs.jackson.annotations)
    implementation(libs.jackson.dataformat.xml)
    implementation(libs.spring.boot.starter.jackson)
    implementation(libs.spring.boot.starter.logging)
    // Needed to put the geoclient.xml file on the classpath for testing
    testImplementation(testFixtures(project(':geoclient-core')))
}
